### ISSUE TITLE
Add a feature to delete document

### ISSUE THREAD

**Issue by chacha912** [yorkie-team/dashboard#110]
**Description**:

The feature to delete documents has been implemented in https://github.com/yorkie-team/yorkie/pull/484.
Let's provide a UI in the dashboard to delete documents.

- On the document detail page:
![image](https://user-images.githubusercontent.com/81357083/230052092-7bc9d670-9ccd-49e7-845f-ca851b8d5525.png)
- On the document list page: 
![image](https://user-images.githubusercontent.com/81357083/230052839-a57eaee1-4dcf-4da5-8dc4-99d4360d3d4d.png)

**Why**: Users can delete document.

**Comment by hackerwins** [comment]
We need to add the deletion UI to the document detail page as well.
