### ISSUE TITLE
Modify variable spelling

### ISSUE THREAD

**Issue by iyu88** [yorkie-team/dashboard#115]
**Description**:

In PR #114, I think that I found a subtle misspelling.

<img width="598" alt="스크린샷 2023-04-28 09 39 28" src="https://user-images.githubusercontent.com/31645195/235025129-4997842b-c528-44d4-bab1-a39f46d21827.png">

[DocumentList.tsx](https://github.com/yorkie-team/dashboard/pull/114/files#diff-10894439bac1aa0794d96ae7a24ab83198f1f1e652a2173f81d148fb2f36fa42)

I think `previousProjectName` is more accurate spelling.

So it would better to remove 'e'.

**Why**:

Grammarly spelling ensures that code understanding is not impaired.

**Comment by mihilt** [comment]
I feel ashamed..😅 It was my mistake, so I'll take care of it. Thank you for letting me know about it.
