### ISSUE TITLE
Add exception handling when project name contains characters not allowed

### ISSUE THREAD

**Issue by devleejb** [yorkie-team/dashboard#124]
https://github.com/yorkie-team/dashboard/assets/52884648/13c85a39-3390-4614-b953-f28ae5885182

**Description**:
- Add exception handling when project name contains characters not allowed(Capital letters, Korean, ...)
    - Alert when create project with capital letters  or display project naming rule

**Why**:
- No notification when project name does not comply with rules

**Comment by devleejb** [comment]
It works well in dev mode.

**Comment by chacha912** [comment]
As this issue no longer seems to occur, I'll be closing it.

<img width="500" alt="" src="https://github.com/user-attachments/assets/17428f86-7678-4a21-8b23-689bb84554fd">
