### ISSUE TITLE
Duplicate documents with the same key are shown on Dashboard

### ISSUE THREAD

**Issue by hackerwins** [yorkie-team/dashboard#137]
**Description**:

Duplicate documents with the same key are shown on the Dashboard.

1. Create a document and remove it with Yorkie CLI.
2. Add another document with the same key.
3. View the Dashboard where the documents are displayed.
4. Note the duplication of documents with the same key.

This issue seems to be reproducible when using the force option in Yorkie CLI to forcefully delete documents.

- https://yorkie.dev/docs/cli#removing-a-document
- https://github.com/yorkie-team/yorkie/issues/758

**Comment by hackerwins** [comment]
![스크린샷 2024-03-05 오후 1 59 22](https://github.com/yorkie-team/dashboard/assets/2059311/3c681ede-b56b-4440-bd64-8847a80ff36f)

**Comment by chacha912** [comment]
This issue was resolved by https://github.com/yorkie-team/yorkie/pull/907.
(Ref: https://github.com/yorkie-team/yorkie/issues/758)
