### ISSUE TITLE
[suggestion] migration moment.js to date-fns

### ISSUE THREAD

**Issue by DongjaJ** [yorkie-team/dashboard#140]
**Description**:
migration moment.js to date-fns

**Why**:
Moment is lagacy project. And it might cause a huge performance overhead because of its complex APIs and large bundle size.

[moment docs](https://momentjs.com/docs)
[You-Dont-Need-Momentjs](https://github.com/you-dont-need/You-Dont-Need-Momentjs/blob/master/README.md)

**Comment by hackerwins** [comment]
Thank you for your good comments.
Could you send a PR for this?

**Comment by DongjaJ** [comment]
Sure! I'll try this

**Comment by hackerwins** [comment]
https://github.com/yorkie-team/dashboard/commit/caae3547329c8a73c2718d75d5218d1d7a978a74
