### ISSUE TITLE
Introduce login button for mobile users

### ISSUE THREAD

**Issue by devleejb** [yorkie-team/dashboard#143]
**Description**:
Currently, the login button is not visible on the mobile page, which creates difficulty for mobile users to access the login page. To improve user experience, it is recommended to introduce a login redirect button that is clearly visible and accessible on the mobile page to direct users to the login page seamlessly.

**Why**:
Enhance the accessibility and usability of the platform for mobile users.

**Comment by devysi0827** [comment]
It appears that this issue has been resolved. I am leaving a comment for notification purposes.

**Comment by devleejb** [comment]
@devysi0827 
Sorry, but it seems this issue is related to the `yorkie-team/yorkie-team.github.io` repository. I have clarified this bug and created a new issue here: https://github.com/yorkie-team/yorkie-team.github.io/issues/146. Please refer to that issue.

I will close this issue now.
