### ISSUE TITLE
Getting error "protoc-gen-js: program not found or is not executable" when "npm run build:proto"

### ISSUE THREAD

**Issue by DongjinS** [yorkie-team/dashboard#24]
**Description**:

"npm run build:proto" makes error  "protoc-gen-js: program not found or is not executable" with **protoc version 3.21.1.**

After downgrade **protoc version to 3.19.4**, "npm run build:proto" makes **no error**. (refer https://github.com/protocolbuffers/protobuf-javascript/issues/105)

"npm run build" script in `package.json` need to be changed for work with the latest version of protocol or read.me should tell me the appropriate protocol version.

**Why**:
Can work with the latest version of protocol buffer.

**Comment by hackerwins** [comment]
Below is a guide to installing protoc-gen-js.
https://github.com/grpc/grpc-web#code-generator-plugin
